### ISSUE TITLE
Cannot compile 

### ISSUE THREAD

**Issue by joanassum** [EmpireCTF/ctfdojo#1]
I tried to compile the code following the instruction but it gives the following error
`Main.hx:26: characters 16-18 : Unexpected ->`

I have haxe version 3.4.7 and I didn't change anything from the Config.hx template.

**Comment by Aurel300** [comment]
Thanks! I knew I forgot something. Use a newer version of Haxe, e.g. the [4.0.0 release candidate](https://haxe.org/download/version/4.0.0-rc.1/). I'll put this into the README after today's session.
